global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'app-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8000']
    scheme: http
    metrics_path: /metrics

  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8000']
    scheme: http

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scheme: http

  - job_name: 'test-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['test-app:8000']
    scheme: http
    # Add labels to metrics from this job
    relabel_configs:
      - source_labels: [__address__]
        target_label: __metrics_path__
        regex: (.+)
        replacement: /metrics
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: ${1}:8000
      - target_label: job
        replacement: 'test-app'

  # Blackbox exporter for HTTP/HTTPS checks
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://test-app:8000  # Test application
        - http://prometheus:9090  # Prometheus UI
        - http://grafana:3000  # Grafana UI
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Blackbox exporter service

  # Alertmanager metrics
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  # Node exporter metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
