global:
  resolve_timeout: 5m
  # SMTP configuration for email notifications (optional)
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your-email@gmail.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-password'
  smtp_require_tls: true

# Route configuration defines how alerts are processed
route:
  # Default receiver if an alert doesn't match any routes
  receiver: 'telegram-default'
  
  # Group alerts by these labels
  group_by: ['alertname', 'severity']
  
  # Initial delay before sending first notification for a new group
  group_wait: 30s
  
  # Delay between sending notifications about new groups
  group_interval: 5m
  
  # How long to wait before sending a notification again if it has already been sent
  repeat_interval: 1h
  
  # Child routes for different alert severities
  routes:
    - match:
        severity: 'critical'
      receiver: 'telegram-critical'
      continue: true
      
    - match:
        severity: 'warning'
      receiver: 'telegram-warning'
      continue: true

# Receivers define how to send notifications
receivers:
  - name: 'telegram-default'
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        bot_token: 'YOUR_BOT_TOKEN'
        chat_id: YOUR_CHAT_ID
        message: '{{ template "telegram.default.message" . }}'
        parse_mode: 'HTML'
        send_resolved: true
        
  - name: 'telegram-critical'
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        bot_token: 'YOUR_BOT_TOKEN'
        chat_id: YOUR_CHAT_ID
        message: '🚨 <b>CRITICAL ALERT</b>\n{{ template "telegram.default.message" . }}'
        parse_mode: 'HTML'
        send_resolved: true
        
  - name: 'telegram-warning'
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        bot_token: 'YOUR_BOT_TOKEN'
        chat_id: YOUR_CHAT_ID
        message: '⚠️ <b>WARNING</b>\n{{ template "telegram.default.message" . }}'
        parse_mode: 'HTML'
        send_resolved: true

# Templates for notification messages
templates:
  - '/etc/alertmanager/telegram.tmpl'
